### ISSUE TITLE
about Strip //ui/views from Chromium?

### ISSUE THREAD

**Issue by bizehao** [photoionization/chrohime#2]
I have tried to separate //ui/views from chromium before, but failed because there are too many dependencies. I want to ask if it is necessary to do the separation

**Comment by zcbenz** [comment]
Sorry for the very late reply. Stripping the dependencies is simply impossible, and exporting raw C++ APIs of `//ui/view` is close to impossible as it does not hide the dependences in its headers.

That's why I'm doing a C library: in this way I can just hide the dependencies behind the C header.
